services:
  api:
    image: pdf-extractext-api:0.1.0
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=PDF Extractext API
      - APP_VERSION=0.1.0
      - APP_MAX_PDF_SIZE_BYTES=5242880
      - MONGODB_URI=mongodb://host.docker.internal:27017
      - MONGODB_DB_NAME=pdf-extractext
    extra_hosts:
      - "host.docker.internal:host-gateway"
