# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python 3.14
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        
        python -m pip install --upgrade pip
        pip install pypdf[all] fastapi[all] uvicorn[standard] httpx2 python-multipart PyMuPDF pytesseract pymongo python-dotenv Pillow ruff pytest pytest-mock requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
    - name: Lint and check format with ruff
      run: |
        # Run ruff linter and output in GitHub Actions format
        ruff check --output-format=github .
        # Check formatting (this will fail the build if files are not formatted)
        ruff format --check .
    - name: Test with pytest
      run: |
        xvfb-run pytest